name: Top GitHub Users
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
jobs:
  release:
    name: GitHub Active Users
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.CUSTOM_TOKEN }}
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.17.0
      - uses: gayanvoice/top-github-users-action@master
        env:
          CUSTOM_TOKEN: ${{ secrets.CUSTOM_TOKEN }}
          with:
          branch: main
          commit_user_email: "117867334+xiv3r@users.noreply.github.com"
          commit_author: xiv3r <"117867334+xiv3r@users.noreply.github.com">
